### ISSUE TITLE
Does not boot on EFI syslinux

### ISSUE THREAD

**Issue by benthetechguy** [ipxe/wimboot#28]
Hello, this is the config I'm using to load Windows 10 install media via syslinux with wimboot:
```
LABEL windows
    KERNEL linux.c32
    APPEND wimboot initrdfile=/boot/bcd,/boot/boot.sdi,/sources/boot.wim
```
It works perfectly on BIOS syslinux, but on EFI syslinux, after it finishes "encapsulating" all the files, it simply reboots.

**Comment by NiKiZe** [comment]
Wimboot is an efi binary, you will need to call it as such and not a Linux kernel (this of course applies to efi mode)

**Comment by benthetechguy** [comment]
That's unfortunate, since syslinux lacks the ability to chain load efi binaries. Are there any workarounds you can think of for this?

**Comment by NiKiZe** [comment]
If you are running in efi mode then you must run efi version of iPXE as well. It is odd that efi version of syslinux can't run efi binaries.

**Comment by benthetechguy** [comment]
Definitely. Development on syslinux stagnated around 2014, so not much work has gone into EFI stuff for syslinux and it barely has any features as a result. Is there a way for me to load iPXE from syslinux? Like a linux kernel version of iPXE I can load?

**Comment by NiKiZe** [comment]
Again, you have 2 modes, pcbios or efi, the underlying system needs to exist for Wimboot to work and hook into. To have it use any underlaying efi functions, you must start it as an efi binary. If you can't do that, then run the system in pcbios mode.

**Comment by benthetechguy** [comment]
No, I cannot simply switch to legacy BIOS mode; as time goes on, more and more PCs no longer have a CSM, including some of the ones I need to PXE boot.

What I was asking about was if it's possible to load iPXE from EFI syslinux, to then run wimboot from there. There's `undionly.kpxe`, but pxechn.c32 is only for bios syslinux. There's `ipxe.efi`, but as we've already established syslinux cannot chainload efi binaries.

I was able to find [some patches for iPXE](https://lists.ipxe.org/pipermail/ipxe-devel/2018-November/006338.html) on a post in the iPXE mailing list that, according to the poster and [this proof of concept](https://github.com/Sporesirius/syslinuxefi-wimboot), allow loading it as a Linux kernel on UEFI. The underlying EFI functions you were talking about are perfectly there when loading it as a linux kernel in EFI syslinux, just not taken advantage of.

**Comment by NiKiZe** [comment]
My mistake for mixing between iPXE and wimboot, so to be clear, when iPXE undionly.kpxe is built, there is never any efi code in there. When snponly.efi is built then there is no pcbios code in there.

The patches you mention is for wimboot which has support for both at the same time. The same can not be done in iPXE.

**Comment by benthetechguy** [comment]
> The patches you mention are for wimboot

Yeah, I mixed wimboot and iPXE up just like you did, lol. These patches
can't be applied directly to the current wimboot because they're from a
couple years ago and things have changed a bit, but two different sources
say that they work, so there has to be some modern use to them. Maybe
someone smarter than me can figure out how they could be of use in modern
wimboot and start a pull request or something? I believe it's now the only
solution to this problem other than not using syslinux at all since
syslinux can't load much other than Linux kernels.

**Comment by mcb30** [comment]
I have a cleaned-up patch that implements the (deprecated) EFI handover entry point and so should allow `syslinux.efi` to load wimboot.

However, I am unable to locate a working copy of `syslinux.efi` to test with.  The version from the Fedora RPM triggers an assertion failure in the OVMF firmware, and I am unable to rebuild syslinux from source due to multiple build errors.

@benthetechguy could you please provide a known-working source tree (or prebuilt binaries) for `syslinux.efi`?

**Comment by mcb30** [comment]
> I have a cleaned-up patch that implements the (deprecated) EFI handover entry point and so should allow `syslinux.efi` to load wimboot.

Completely untested code is in the https://github.com/ipxe/wimboot/tree/efi_handover branch.

**Comment by benthetechguy** [comment]
> Could you please provide a known-working source tree (or prebuilt
binaries) for `syslinux.efi`?

Here's the official binary, syslinux.efi and all the modules and things you
need are inside:
https://mirrors.edge.kernel.org/pub/linux/utils/boot/syslinux/syslinux-6.03.tar.xz

>
I'll try out your testing branch soon, thank you!

**Comment by mcb30** [comment]
> Here's the official binary, syslinux.efi and all the modules and things you need are inside: https://mirrors.edge.kernel.org/pub/linux/utils/boot/syslinux/syslinux-6.03.tar.xz

Thanks.  It now gets as far as downloading `ldlinux.e64` via TFTP, and then exits.  I don't see any TFTP request for a configuration file.  Any suggestions?

**Comment by benthetechguy** [comment]
Just compiled and tested your new branch; unfortunately it still reboots the system after it finishes encapsulating like before.

**Comment by mcb30** [comment]
With the syslinux-6.03 prebuilt binaries I am able to get as far as attempting to load the modified `wimboot`.  It fails to execute with `syslinux.efi` reporting the error `Cannot relocate kernel, bailing out`.  This error arises because `wimboot` cannot be loaded at its preferred address (around 0x20000 in base memory), presumably because something else is already occupying that memory.

I have verified that the same failure arises with a version of wimboot patched exactly as per https://lists.ipxe.org/pipermail/ipxe-devel/2018-November/006338.html

It would potentially be possible to add support for self-relocation, which would allow `syslinux.efi` to load `wimboot` at an alternative address.  However, there is no way to mark the image as relocatable for UEFI without also marking it as relocatable for BIOS: we would therefore have to also support relocation as a BIOS bzImage.

This seems like a reasonably high effort simply in order to maintain compatibility with the effectively unsupported EFI version of syslinux.  Unless there's a compelling reason to do otherwise, I would therefore suggest that you replace your syslinux boot flow with iPXE.

**Comment by benthetechguy** [comment]
Alright. I don't have much control over our PXE system, but I'll try to convince them to let me set up iPXE. There's all kinds of benefits with HTTP everywhere and so many more boot possibilities. Thank you for your help!
